import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Sparkles, Upload, Search, Monitor, Wand2, ChevronDown, ChevronUp, Loader2, X, Brain, Film, Mic, Zap, Smartphone, PartyPopper, CheckCircle } from 'lucide-react'
import { supabase, db } from '@/lib/supabase'
import { useAuth } from '@/hooks/useAuth'
import { PLATFORMS, TONES } from '@/constants/platforms'
import { isImageGenConfigured } from '@/lib/image-gen'
import type { Platform } from '@/types/database'

const PIPELINE_STAGES = [
  { key: 'strategy', label: 'Strategy & Scripting', icon: <Brain size={18} />, desc: 'Analyzing niche and crafting viral hooks' },
  { key: 'voice', label: 'AI Voiceover', icon: <Mic size={18} />, desc: 'Generating human-like narration (ElevenLabs)' },
  { key: 'assets', label: 'Visual Sourcing', icon: <Film size={18} />, desc: 'Sourcing stock and generating AI visuals' },
  { key: 'assembly', label: 'Video Rendering', icon: <Zap size={18} />, desc: 'Burning captions and syncing audio' },
  { key: 'adapt', label: 'Platform Optimization', icon: <Smartphone size={18} />, desc: 'Exporting native versions for each platform' },
]

const FACELESS_NICHES = [
  { id: 'custom', label: 'Custom Prompt', icon: '✨', desc: 'Describe your own unique idea' },
  { id: 'reddit', label: 'Reddit Stories', icon: '🤖', desc: 'TDA, AITA, or creepy Reddit threads' },
  { id: 'motivation', label: 'Motivational', icon: '🔥', desc: 'Deep quotes with cinematic visuals' },
  { id: 'horror', label: 'Horror / Mystery', icon: '👻', desc: 'Scary stories and urban legends' },
  { id: 'finance', label: 'Finance / Wealth', icon: '💰', desc: 'Daily market news or wealth tips' },
  { id: 'facts', label: 'Did You Know?', icon: '💡', desc: 'Mind-blowing facts and trivia' },
]

const VOICES = [
  { id: 'adam', label: 'Adam (Deep)', desc: 'Professional, deep male voice' },
  { id: 'bella', label: 'Bella (Soft)', desc: 'Kind, soft female voice' },
  { id: 'antoni', label: 'Antoni (News)', desc: 'Clear, authoritative news voice' },
  { id: 'rachel', label: 'Rachel (Casual)', desc: 'Friendly, upbeat female voice' },
  { id: 'liam', label: 'Liam (Hormozi)', desc: 'Aggressive, high-energy marketing voice' },
]

const SOURCE_MODES = [
  { id: 'stock', icon: <Search size={16} />, label: 'AI + Stock', desc: 'Smart mix of stock and AI-generated media' },
  { id: 'ai_gen', icon: <Wand2 size={16} />, label: 'Full AI Gen', desc: 'Every scene generated by Stable Diffusion/Flux' },
  { id: 'upload', icon: <Upload size={16} />, label: 'My Media', desc: 'Overlay AI voice on your own footage' },
]

export function CreatePage() {
  const { user, subscription } = useAuth()
  const navigate = useNavigate()
  const [prompt, setPrompt] = useState('')
  const [selectedNiche, setSelectedNiche] = useState('custom')
  const [selectedVoice, setSelectedVoice] = useState('adam')
  const [selectedPlatforms, setSelectedPlatforms] = useState<Platform[]>(['tiktok', 'instagram'])
  const [sourceMode, setSourceMode] = useState<'upload' | 'stock' | 'ai_gen'>('stock')
  const [tone, setTone] = useState('casual')
  const [musicMood, setMusicMood] = useState('upbeat')
  const [videoLength, setVideoLength] = useState(60)
  const [showAdvanced, setShowAdvanced] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [pipelineStage, setPipelineStage] = useState(-1)
  const [error, setError] = useState<string | null>(null)
  const [imageStyle, setImageStyle] = useState<'photorealistic' | 'illustration' | 'cinematic' | 'anime' | '3d-render' | 'flat-design'>('photorealistic')
  const [imageAspectRatio, setImageAspectRatio] = useState<'9:16' | '1:1' | '16:9'>('9:16')
  const imageGenAvailable = isImageGenConfigured()

  const visibleStages = PIPELINE_STAGES

  function togglePlatform(id: Platform) {
    setSelectedPlatforms(prev =>
      prev.includes(id) ? prev.filter(p => p !== id) : [...prev, id]
    )
  }

  const canGenerate = (selectedNiche !== 'custom' || prompt.trim().length > 10) && selectedPlatforms.length > 0 && !generating

  async function handleGenerate() {
    if (!canGenerate || !user) return
    if (subscription && subscription.posts_used_this_month >= subscription.posts_limit && subscription.posts_limit !== -1) {
      setError('You have reached your monthly post limit. Please upgrade your plan.')
      return
    }
    setError(null)
    setGenerating(true)
    setPipelineStage(0)

    const finalPrompt = selectedNiche === 'custom' ? prompt.trim() : `Create a ${FACELESS_NICHES.find(n => n.id === selectedNiche)?.label} video about: ${prompt || 'trending topics in this niche'}`

    // Create the job record
    const { data: job, error: jobErr } = await db.from('content_jobs').insert({
      user_id: user.id,
      prompt: finalPrompt,
      status: 'pending',
      platforms: selectedPlatforms,
      source_mode: sourceMode === 'stock' ? 'stock' : sourceMode,
      tone,
      music_mood: musicMood,
      video_length: videoLength,
      pipeline_stage: 'Initializing',
      pipeline_progress: 0,
      voice_id: selectedVoice,
      niche: selectedNiche,
      image_style: (sourceMode === 'ai_gen' || sourceMode === 'stock') ? imageStyle : null,
      image_aspect_ratio: (sourceMode === 'ai_gen' || sourceMode === 'stock') ? imageAspectRatio : null,
    }).select().single()

    if (jobErr || !job) {
      setError('Failed to create job. Please try again.')
      setGenerating(false)
      return
    }

    const stages = visibleStages.map((_s, i) => ({ stage: i, delay: i * 3500 }))
    stages.forEach(({ stage, delay }) => {
      setTimeout(() => setPipelineStage(stage), delay)
    })

    // Trigger Vercel API route for content generation
    try {
      const { data: { session } } = await supabase.auth.getSession()
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session?.access_token ?? ''}`,
        },
        body: JSON.stringify({
          jobId: job.id,
          prompt: finalPrompt,
          platforms: selectedPlatforms,
          sourceMode,
          tone,
          musicMood,
          videoLength,
          voiceId: selectedVoice,
          imageStyle: (sourceMode === 'ai_gen' || sourceMode === 'stock') ? imageStyle : undefined,
          imageAspectRatio: (sourceMode === 'ai_gen' || sourceMode === 'stock') ? imageAspectRatio : undefined,
        }),
      })

      if (!res.ok) throw new Error(await res.text())

      setPipelineStage(PIPELINE_STAGES.length)
      setTimeout(() => navigate(`/review/${job.id}`), 800)
    } catch {
      // Job was created — navigate to review even if generation fails gracefully
      setTimeout(() => navigate(`/review/${job.id}`), 1500)
    }
  }

  if (generating) {
    return (
      <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24 }}>
        <div style={{ width: '100%', maxWidth: 560, textAlign: 'center' }}>
          <div style={{ fontSize: 48, marginBottom: 20, animation: pipelineStage >= visibleStages.length ? 'celebrate-bounce 0.6s ease' : 'none' }}>
            {pipelineStage >= 0 && pipelineStage < visibleStages.length ? visibleStages[pipelineStage].icon : <PartyPopper size={40} color="#00E5A0" />}
          </div>
          <h2 style={{ fontFamily: 'Syne', fontSize: 24, fontWeight: 700, color: '#F0F4F8', marginBottom: 8 }}>
            {pipelineStage >= visibleStages.length ? 'Your Reels are ready!' : 'Assembling Faceless Content…'}
          </h2>
          <p style={{ color: '#8B9EB0', fontSize: 14, marginBottom: 32 }}>
            {pipelineStage >= visibleStages.length ? 'We\'ve generated all platform versions. Review and approve them before they go live.' : `Currently: ${visibleStages[pipelineStage]?.label || 'Loading…'}`}
          </p>

          <div style={{ background: '#0F1318', border: '1px solid #1E2A36', borderRadius: 16, padding: 24, textAlign: 'left' }}>
            {visibleStages.map((stage, i) => (
              <div key={stage.key} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '10px 0',              borderBottom: i < visibleStages.length - 1 ? '1px solid #1E2A36' : 'none'  }}>
                <div style={{
                  width: 32, height: 32, borderRadius: '50%',
                  background: i < pipelineStage ? '#00E5A0' : i === pipelineStage ? 'rgba(0,229,160,0.15)' : '#1E2A36',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: i < pipelineStage ? 14 : 18, flexShrink: 0,
                  transition: 'all 0.4s',
                }}>
                  {i < pipelineStage ? <CheckCircle size={14} color="#00E5A0" /> : stage.icon}
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: 13, fontFamily: 'Syne', fontWeight: 600, color: i <= pipelineStage ? '#F0F4F8' : '#4A5E70' }}>
                    {stage.label}
                  </div>
                  {i === pipelineStage && (
                    <div style={{ fontSize: 11, color: '#8B9EB0', marginTop: 2 }}>{stage.desc}</div>
                  )}
                </div>
                {i === pipelineStage && (
                  <Loader2 size={14} color="#00E5A0" className="animate-spin" />
                )}
                {i < pipelineStage && (
                  <div style={{ fontSize: 11, color: '#00E5A0', fontFamily: 'JetBrains Mono' }}>READY</div>
                )}
              </div>
            ))}
          </div>

          <div className="progress-bar" style={{ marginTop: 20 }}>
            <div className="progress-bar-fill" style={{ width: `${Math.round(((pipelineStage + 1) / visibleStages.length) * 100)}%`, transition: 'width 1s ease' }} />
          </div>
        </div>
      </div>
    )
  }

  return (
    <div style={{ maxWidth: 900, margin: '0 auto', padding: 28 }}>
      <div style={{ marginBottom: 32 }}>
        <h1 style={{ fontFamily: 'Syne', fontSize: 28, fontWeight: 700, color: '#F0F4F8', marginBottom: 6 }}>Create Faceless Reels</h1>
        <p style={{ color: '#8B9EB0', fontSize: 15 }}>Pick a niche, select a voice, and let AI handle the rest.</p>
      </div>

      {/* Faceless Niches */}
      <div style={{ marginBottom: 32 }}>
        <label style={{ fontSize: 12, color: '#8B9EB0', display: 'block', marginBottom: 12, fontFamily: 'JetBrains Mono', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
          1. Select Your Niche
        </label>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: 12 }}>
          {FACELESS_NICHES.map(n => (
            <button
              key={n.id}
              onClick={() => setSelectedNiche(n.id)}
              style={{
                display: 'flex', alignItems: 'center', gap: 12, padding: '14px 16px',
                borderRadius: 12, background: selectedNiche === n.id ? 'rgba(0,229,160,0.06)' : '#161C24',
                border: `1px solid ${selectedNiche === n.id ? '#00E5A0' : '#1E2A36'}`,
                textAlign: 'left', cursor: 'pointer', transition: 'all 0.2s',
              }}
            >
              <span style={{ fontSize: 24 }}>{n.icon}</span>
              <div>
                <div style={{ fontSize: 14, fontWeight: 700, color: selectedNiche === n.id ? '#00E5A0' : '#F0F4F8', fontFamily: 'Syne' }}>{n.label}</div>
                <div style={{ fontSize: 11, color: '#8B9EB0' }}>{n.desc}</div>
              </div>
            </button>
          ))}
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1.5fr 1fr', gap: 32, marginBottom: 32 }}>
        {/* Left Col: Prompt & Platform */}
        <div>
          <div style={{ marginBottom: 24 }}>
            <label style={{ fontSize: 12, color: '#8B9EB0', display: 'block', marginBottom: 8, fontFamily: 'JetBrains Mono', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              2. Content Description
            </label>
            <textarea
              className="input-base"
              placeholder={selectedNiche === 'reddit' ? 'Paste the Reddit story link or text here…' : 'Describe the topic or specific content you want…'}
              value={prompt}
              onChange={e => setPrompt(e.target.value)}
              style={{ minHeight: 120, resize: 'vertical', fontSize: 15, lineHeight: 1.6 }}
            />
          </div>

          <div style={{ marginBottom: 0 }}>
            <label style={{ fontSize: 12, color: '#8B9EB0', display: 'block', marginBottom: 8, fontFamily: 'JetBrains Mono', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              3. Target Platforms
            </label>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
              {PLATFORMS.slice(0, 3).map(p => {
                const selected = selectedPlatforms.includes(p.id)
                return (
                  <button
                    key={p.id}
                    onClick={() => togglePlatform(p.id)}
                    style={{
                      display: 'flex', alignItems: 'center', gap: 6,
                      padding: '8px 16px', borderRadius: 20,
                      background: selected ? p.bgColor : '#161C24',
                      border: `1px solid ${selected ? p.color : '#1E2A36'}`,
                      color: selected ? '#F0F4F8' : '#8B9EB0',
                      cursor: 'pointer', fontSize: 13,
                      transition: 'all 0.2s',
                    }}
                  >
                    <span style={{ fontSize: 16 }}>{p.icon}</span>
                    {p.name}
                  </button>
                )
              })}
            </div>
          </div>
        </div>

        {/* Right Col: Voice & Media */}
        <div>
          <div style={{ marginBottom: 24 }}>
            <label style={{ fontSize: 12, color: '#8B9EB0', display: 'block', marginBottom: 8, fontFamily: 'JetBrains Mono', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              4. AI Voiceover
            </label>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {VOICES.map(v => (
                <button
                  key={v.id}
                  onClick={() => setSelectedVoice(v.id)}
                  style={{
                    display: 'flex', alignItems: 'center', gap: 10, padding: '10px 14px',
                    borderRadius: 10, background: selectedVoice === v.id ? 'rgba(0,180,216,0.06)' : '#161C24',
                    border: `1px solid ${selectedVoice === v.id ? '#00B4D8' : '#1E2A36'}`,
                    textAlign: 'left', cursor: 'pointer', transition: 'all 0.2s',
                  }}
                >
                  <div style={{ width: 24, height: 24, borderRadius: '50%', background: selectedVoice === v.id ? '#00B4D8' : '#1E2A36', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <Mic size={12} color={selectedVoice === v.id ? '#080B0F' : '#8B9EB0'} />
                  </div>
                  <div>
                    <div style={{ fontSize: 13, fontWeight: 700, color: selectedVoice === v.id ? '#00B4D8' : '#F0F4F8' }}>{v.label}</div>
                    <div style={{ fontSize: 10, color: '#8B9EB0' }}>{v.desc}</div>
                  </div>
                </button>
              ))}
            </div>
          </div>

          <div>
            <label style={{ fontSize: 12, color: '#8B9EB0', display: 'block', marginBottom: 8, fontFamily: 'JetBrains Mono', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
              5. Media Engine
            </label>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: 8 }}>
              {SOURCE_MODES.map(m => (
                <button
                  key={m.id}
                  onClick={() => setSourceMode(m.id as typeof sourceMode)}
                  style={{
                    padding: '10px 14px', borderRadius: 10, textAlign: 'left',
                    background: sourceMode === m.id ? 'rgba(0,229,160,0.06)' : '#161C24',
                    border: `1px solid ${sourceMode === m.id ? '#00E5A0' : '#1E2A36'}`,
                    cursor: 'pointer', transition: 'all 0.2s',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: 6, color: sourceMode === m.id ? '#00E5A0' : '#8B9EB0' }}>
                    {m.icon}
                    <span style={{ fontSize: 13, fontWeight: 600, fontFamily: 'Syne', color: sourceMode === m.id ? '#00E5A0' : '#F0F4F8' }}>{m.label}</span>
                  </div>
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Advanced toggle */}
      <div style={{ marginBottom: 32 }}>
        <button
          onClick={() => setShowAdvanced(!showAdvanced)}
          style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'none', border: 'none', color: '#8B9EB0', cursor: 'pointer', fontSize: 13, padding: 0 }}
        >
          {showAdvanced ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
          Visual Settings & Style
        </button>

        {showAdvanced && (
          <div className="animate-slide-up" style={{ marginTop: 16, background: '#0F1318', border: '1px solid #1E2A36', borderRadius: 12, padding: 20, display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16 }}>
            <div>
              <label style={{ fontSize: 11, color: '#8B9EB0', display: 'block', marginBottom: 8 }}>Image Style</label>
              <select className="input-base" value={imageStyle} onChange={e => setImageStyle(e.target.value as typeof imageStyle)}>
                <option value="photorealistic">📸 Photorealistic</option>
                <option value="cinematic">🎬 Cinematic</option>
                <option value="illustration">🎨 Illustration</option>
                <option value="3d-render">🧊 3D Render</option>
              </select>
            </div>
            <div>
              <label style={{ fontSize: 11, color: '#8B9EB0', display: 'block', marginBottom: 8 }}>Music Mood</label>
              <select className="input-base" value={musicMood} onChange={e => setMusicMood(e.target.value)}>
                {['upbeat', 'dramatic', 'inspirational', 'horror', 'none'].map(m => (
                  <option key={m} value={m}>{m.charAt(0).toUpperCase() + m.slice(1)}</option>
                ))}
              </select>
            </div>
            <div>
              <label style={{ fontSize: 11, color: '#8B9EB0', display: 'block', marginBottom: 8 }}>Video Length</label>
              <select className="input-base" value={videoLength} onChange={e => setVideoLength(Number(e.target.value))}>
                <option value={30}>30 Seconds</option>
                <option value={60}>60 Seconds</option>
                <option value={90}>90 Seconds</option>
              </select>
            </div>
          </div>
        )}
      </div>

      {error && (
        <div style={{ background: 'rgba(255,71,87,0.1)', border: '1px solid rgba(255,71,87,0.2)', borderRadius: 8, padding: '10px 14px', fontSize: 13, color: '#FF4757', marginBottom: 20, display: 'flex', alignItems: 'center', gap: 8 }}>
          <X size={14} />
          {error}
        </div>
      )}

      {/* Generate button */}
      <button
        onClick={handleGenerate}
        disabled={!canGenerate}
        className="btn-primary"
        style={{ width: '100%', justifyContent: 'center', padding: '16px 24px', fontSize: 17, borderRadius: 14, boxShadow: '0 8px 30px rgba(0,229,160,0.15)' }}
      >
        <Sparkles size={20} />
        Generate Faceless Reels
      </button>

      <p style={{ textAlign: 'center', fontSize: 12, color: '#4A5E70', marginTop: 16 }}>
        Estimated rendering time: 3 minutes · Uses 1 creation credit
      </p>
    </div>
  )
}
